name: Deploy Site
on:
  push:
    branches:
      - master
jobs:
  deploy:
    concurrency:
      group: '${{ github.workflow }}-${{ github.ref }}'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          extended: true
          hugo-version: '0.119.0'
      - name: Build
        run: hugo --minify
      - env:
          BRANCH: public
          FOLDER: public
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MESSAGE: 'Build: ({sha}) {msg}'
          REPO: self
          SQUASH_HISTORY: true
        name: Push
        uses: s0/git-publish-subdir-action@develop
